use_frameworks!

target 'ShipBookSDK_Example' do
  pod 'ShipBookSDK', :path => '../'

  target 'ShipBookSDK_Tests' do
    inherit! :search_paths
    platform :ios, '10.0'
    pod 'ShipBookSDK', :path => '../'

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
